### ISSUE TITLE
What changes are needed for "make check" to work

### ISSUE THREAD

**Issue by danielmotaleite** [nigoroll/libvmod-dynamic#1]
You say ```The test suite may not currently run without global (but minor) changes to your system. ``` , but make no reference on what to change for then to work.

Please add  some more info

Thanks

**Comment by Dridi** [comment]
Hello,

Basically, `*.localhost` should resolve to `127.0.0.1`, which is the case on my system with no modification.

I think the test suite specifically uses `img.localhost` and `www.localhost`. You can put entries in your hosts file for instance.

Dridi

**Comment by danielmotaleite** [comment]
Thanks for the info. Maybe it should be better to replace the above phrase with this:

> For the test to work, please add this line to your /etc/hosts:
> `127.0.0.1 www.localhost img.localhost`

So this is clear what is needed

By the way, any idea (weeks, months years?) when the support for varnish5 will be ready?

Again, thanks for the help and for the plugin

**Comment by Dridi** [comment]
> By the way, any idea (weeks, months years?) when the support for varnish5 will be ready?

Feel free to try a pull request, I have no idea when @nigoroll will have time to work on it.

**Comment by nigoroll** [comment]
let's do this after https://github.com/varnishcache/libvmod-example/pull/2

**Comment by nigoroll** [comment]
@danielmotaleite can you please try c140ea3bf1d922ecbcc242419564ecd29dbb94f5 with 5.0 ?
I suspect we only needed a tiny change for 5.0, but as I've only recently adopted this vmod, I'd appreciate an independent test.

**Comment by Dridi** [comment]
FYI I restored support for 4.1 too, so you should be able to kill the 4.1 branch. It works *on my laptop* against both Varnish 4.1 and 5.0 but you should check for yourself first :)

**Comment by danielmotaleite** [comment]
thanks to both, been testing and this is working fine on both versions

**Comment by Dridi** [comment]
Thanks for confirming, I just removed the 4.1 branch!
