### ISSUE TITLE
7.6 branch

### ISSUE THREAD

**Issue by gquintard** [nigoroll/libvmod-dynamic#122]
can we get a release/branch/tag that will work with an installed Varnish please 7.6.

Right now I'm getting the usual:
```
checking for Varnish... 7.6.0
configure: error: Varnish version trunk or higher is required.
```

**Comment by nigoroll** [comment]
I'd like to get https://github.com/varnishcache/varnish-cache/issues/4183 out of the way (see also https://github.com/nigoroll/libvmod-dynamic/commit/c894acd2e8b9d466a1948fa7c8e2e24c42becaea), then yes.

**Comment by ronald-sz** [comment]
I would also love a 7.6 branch. Thank you.
