### ISSUE TITLE
503 for first page load after starting Varnish, no backends listed

### ISSUE THREAD

**Issue by poshaughnessy** [nigoroll/libvmod-dynamic#129]
Hi. Using this vmod (v7.5) for the first time, need some help please!

When I start Varnish up (Mac, with `sudo varnishd -F -a 127.0.0.1:80 -f $(pwd)/varnish-local.vcl -s file,/tmp,500M`) and run `sudo varnishadm backend.list`, I see an empty list of backends.

And when I try to load the page the first time, I get a `503` error. Varnishlog says `fail errno 61 (Connection refused)`. 

This happens every time I stop and restart Varnish. _After_ the first page load, then the backend does appear in the list, is shown as `healthy`, and subsequent page loads work OK.

The backend application is up the whole time and I can't think why it wouldn't be able to connect the first time. I can't see any logs for the backend application which would indicate a request coming through, for the first page load.

Full varnishlog for the problematic first request:

```
*   << BeReq    >> 3         
-   Begin          bereq 2 fetch
-   VCL_use        boot
-   Timestamp      Start: 1732807418.475018 0.000000 0.000000
-   BereqMethod    GET
-   BereqURL       /ecom/products/<obfuscated>
-   BereqProtocol  HTTP/1.1
-   BereqHeader    Host: localhost
-   BereqHeader    sec-ch-ua: "Google Chrome";v="131", "Chromium";v="131", "Not_A Brand";v="24"
-   BereqHeader    sec-ch-ua-mobile: ?0
-   BereqHeader    sec-ch-ua-platform: "macOS"
-   BereqHeader    Upgrade-Insecure-Requests: 1
-   BereqHeader    User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36
-   BereqHeader    Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7
-   BereqHeader    Sec-Fetch-Site: none
-   BereqHeader    Sec-Fetch-Mode: navigate
-   BereqHeader    Sec-Fetch-User: ?1
-   BereqHeader    Sec-Fetch-Dest: document
-   BereqHeader    Accept-Language: en-GB,en-US;q=0.9,en;q=0.8
-   BereqHeader    X-Forwarded-For: 127.0.0.1
-   BereqHeader    Via: 1.1 HO-LAR17GRWNW7J (Varnish/7.5)
-   BereqHeader    X-Iso-Timestamp: Thu, 28 Nov 2024 15:23:38 GMT
-   BereqHeader    X-Esi-Request: false
-   BereqHeader    X-Has-Token-Session: false
-   BereqHeader    Cookie: X-Has-Token-Session=false
-   BereqHeader    X-Mfe-Type: page
-   BereqHeader    X-Cookie-Consent-Given: false
-   BereqHeader    X-Functional-Cookie-Accepted: false
-   BereqHeader    X-Analytics-Cookie-Accepted: false
-   BereqHeader    X-Advertising-Cookie-Accepted: false
-   BereqHeader    Accept-Encoding: gzip
-   BereqHeader    X-Cache: MISS
-   BereqHeader    X-Varnish: 3
-   VCL_call       BACKEND_FETCH
-   VCL_return     fetch
-   Timestamp      Fetch: 1732807418.475039 0.000020 0.000020
-   FetchError     backend browse(127.0.0.1:9190): fail errno 61 (Connection refused)
-   Timestamp      Beresp: 1732807418.481269 0.006250 0.006229
-   Timestamp      Error: 1732807418.481271 0.006253 0.000002
-   BerespProtocol HTTP/1.1
-   BerespStatus   503
-   BerespReason   Backend fetch failed
-   BerespHeader   Date: Thu, 28 Nov 2024 15:23:38 GMT
-   BerespHeader   Server: Varnish
-   VCL_call       BACKEND_ERROR
-   BerespHeader   X-Log-Priority: ERROR
-   BerespHeader   X-Varnish-Backend: browse
-   BerespHeader   Content-Type: text/html; charset=utf-8
-   BerespHeader   Retry-After: 5
-   VCL_return     deliver
-   Storage        malloc Transient
-   Length         278
-   BereqAcct      0 0 0 0 0 0
-   End            

*   << Request  >> 2         
-   Begin          req 1 rxreq
-   Timestamp      Start: 1732807418.471300 0.000000 0.000000
-   Timestamp      Req: 1732807418.471300 0.000000 0.000000
-   VCL_use        boot
-   ReqStart       127.0.0.1 50574 a0
-   ReqMethod      GET
-   ReqURL         /ecom/products/<obfuscated>
-   ReqProtocol    HTTP/1.1
-   ReqHeader      Host: localhost
-   ReqHeader      Connection: keep-alive
-   ReqHeader      Cache-Control: max-age=0
-   ReqHeader      sec-ch-ua: "Google Chrome";v="131", "Chromium";v="131", "Not_A Brand";v="24"
-   ReqHeader      sec-ch-ua-mobile: ?0
-   ReqHeader      sec-ch-ua-platform: "macOS"
-   ReqHeader      Upgrade-Insecure-Requests: 1
-   ReqHeader      User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36
-   ReqHeader      Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7
-   ReqHeader      Sec-Fetch-Site: none
-   ReqHeader      Sec-Fetch-Mode: navigate
-   ReqHeader      Sec-Fetch-User: ?1
-   ReqHeader      Sec-Fetch-Dest: document
-   ReqHeader      Accept-Encoding: gzip, deflate, br, zstd
-   ReqHeader      Accept-Language: en-GB,en-US;q=0.9,en;q=0.8
-   ReqHeader      Cookie: X-Has-Token-Session=false
-   ReqHeader      X-Forwarded-For: 127.0.0.1
-   ReqHeader      Via: 1.1 HO-LAR17GRWNW7J (Varnish/7.5)
-   VCL_call       RECV
-   ReqHeader      X-Iso-Timestamp: Thu, 28 Nov 2024 15:23:38 GMT
-   ReqHeader      X-Esi-Request: false
-   ReqHeader      X-Has-Token-Session: false
-   VCL_Log        customerId:-1
-   ReqUnset       Cookie: X-Has-Token-Session=false
-   ReqHeader      Cookie: X-Has-Token-Session=false
-   ReqHeader      X-Mfe-Type: page
-   ReqHeader      X-Cookie-Consent-Given: false
-   ReqHeader      X-Functional-Cookie-Accepted: false
-   ReqHeader      X-Analytics-Cookie-Accepted: false
-   ReqHeader      X-Advertising-Cookie-Accepted: false
-   VCL_return     hash
-   ReqUnset       Accept-Encoding: gzip, deflate, br, zstd
-   ReqHeader      Accept-Encoding: gzip
-   VCL_call       HASH
-   VCL_return     lookup
-   VCL_call       MISS
-   ReqHeader      X-Cache: MISS
-   VCL_return     fetch
-   Link           bereq 3 fetch
-   Timestamp      Fetch: 1732807418.481376 0.010076 0.010076
-   RespProtocol   HTTP/1.1
-   RespStatus     503
-   RespReason     Backend fetch failed
-   RespHeader     Date: Thu, 28 Nov 2024 15:23:38 GMT
-   RespHeader     Server: Varnish
-   RespHeader     X-Log-Priority: ERROR
-   RespHeader     X-Varnish-Backend: browse
-   RespHeader     Content-Type: text/html; charset=utf-8
-   RespHeader     Retry-After: 5
-   RespHeader     X-Varnish: 2
-   RespHeader     Age: 0
-   RespHeader     Via: 1.1 HO-LAR17GRWNW7J (Varnish/7.5)
-   VCL_call       DELIVER
-   RespHeader     X-Proxy-Cache: MISS
-   RespHeader     X-Mfe-Type: page
-   RespHeader     Set-Cookie: X-Has-Token-Session=false; path=/; max-age=3600; samesite=strict; secure
-   VCL_return     deliver
-   Timestamp      Process: 1732807418.481394 0.010094 0.000018
-   Filters        
-   RespHeader     Content-Length: 278
-   RespHeader     Connection: keep-alive
-   Timestamp      Resp: 1732807418.481611 0.010311 0.000216
-   ReqAcct        796 0 796 429 278 707
-   End            
```

Relevant parts of the VCL:

```
import dynamic;

...

backend default none;

...

sub vcl_init {
   new browse = dynamic.director(ttl = 15m, connect_timeout = 5s, first_byte_timeout = 30s, between_bytes_timeout = 10s);
   # Other backends...
}

sub vcl_recv {

  ...

  if (<request matching logic here>) {
      set req.backend_hint = browse.backend("localhost", "9190");
  }

  ...
```

(I can't share the whole VCL, but could share other specific bits as needed. I could also try to make a stripped-down VCL for minimal replication if helpful?)

The behaviour I was expecting was for the backends to be initialised at startup, but I might have assumed that incorrectly - on the fly is fine, as long as the first page load can be served correctly?

Thanks v much in advance and for all your work on this vmod, which should be really useful for us!

**Comment by nigoroll** [comment]
First, some clarifications:

> The behaviour I was expecting was for the backends to be initialised at startup.

This is not what happens when you use `<director>.backend()` in `vcl_recv {}` (or any other sub on the client or backend side, for that matter): In this case, the dynamic backend is not created before a request runs the first time, also also it will not show up in `backend.list` before a request is received. This is not by accident, this was the initial motivation for this vmod: To be able to create backends based on information from the request. The alternative mentioned below was added later.

In your particular case, you would not even need a dynamic backend, you could simply use a static backend: `backend browse { .host = "localhost"; .port = "9190") }`.

If you wanted to create a dynamic backend at `vcl_init {}` time, you coud create it below another director and then use that one, as shown in the [`layer.vtc`](https://github.com/nigoroll/libvmod-dynamic/blob/0590f76b05f9b83a5a2e1d246e67a12d66e55c27/src/tests/layer.vtc#L34) test case.

Regarding `FetchError backend browse(127.0.0.1:9190): fail errno 61 (Connection refused)`, [it is emit after vmod_dynamic has run when varnish-cache tries to connect to the backend](https://github.com/varnishcache/varnish-cache/blob/027c91f2166e260d2922e933e27c01cff81a5228/bin/varnishd/cache/cache_backend.c#L284-L286). I can only speculate why you are seeing this behavior, but it seems unrelated to both Varnish-Cache and vmod_dynamic. One thing which comes to mind is that your backend might only listen on IPv6, but `localhost` resolves to both IPv4 and IPv6. In this case, you can use an ACL as shown [here](https://github.com/nigoroll/libvmod-dynamic/blob/0590f76b05f9b83a5a2e1d246e67a12d66e55c27/src/vmod_dynamic.vcc#L627).

**Comment by poshaughnessy** [comment]
Thank you so much, you were totally right that it was to do with IPv4/IPv6 conflict. I followed [an answer here](https://superuser.com/a/36976) and commented out `::1         localhost` from my `/etc/hosts`. It now loads fine on the first page load after restarting Varnish.

Thanks also for the clarification on how it should work. I do not have a need to initialise the backend in `vcl_init`, I just incorrectly though perhaps that was related to the issue of the failed first page loads.

(We don't want to just use static backends because there are other backends which may or may not be accessible in certain environments - currently with static backends, Varnish fails to start up).

Thanks again!
