### ISSUE TITLE
How to see the vmod-dynamic logs

### ISSUE THREAD

**Issue by danielmotaleite** [nigoroll/libvmod-dynamic#15]
Hi

I usually debug varnish using varnishlog, but since i added vmod-dynamic i have the problem that i do not see any log related with vmod-dynamic.

https://github.com/nigoroll/libvmod-dynamic/blob/master/src/vmod_dynamic.vcc seems to say that it should log something, but refers no way to enable that log

So how can enable/check the vmod log? is there any vmod option that i'm unfamiliar with?

Thanks

**Comment by Dridi** [comment]
The logs from this module can happen during or outside transactions. To see the logs from outside transactions, you need raw grouping in `varnishlog`.

You can try this:

```
varnishlog -g raw -q '* ~ vmod-dynamic'
```

**Comment by danielmotaleite** [comment]
Perfect! Thanks for the help!

Can you please add this to the documentation, it is very useful :)

**Comment by Dridi** [comment]
Keeping this one open: although it is documented in Varnish, it's not the first time I got this question. I will close this ticket with a docfix, giving users directions to upstream Varnish docs on logs.
