### ISSUE TITLE
max_connections

### ISSUE THREAD

**Issue by danielmotaleite** [nigoroll/libvmod-dynamic#17]
In normal varnish, we can set the .max_connections in the backend... how to do this with libvmod-dynamic? what is the current max for libvmod-dynamic?

Thanks!

**Comment by Dridi** [comment]
I believe the current is "embarrassingly unbounded". After a quick look, the two properties we are missing are `max_connections` and `proxy_header`. The latter is a bit harder to implement because it's not available on all versions supported by this VMOD.

Assigning to myself, thanks for reporting!

**Comment by danielmotaleite** [comment]
ok, thanks for the info!!
"embarrassingly unbounded" is lot better than "bottleneck to a very low number" :)
So for now i do not need to check this limit when debugging

Again, thanks for the help and for the vmod!
