### ISSUE TITLE
question: is it possible to use dynamic with saintmode?

### ISSUE THREAD

**Issue by danielmotaleite** [nigoroll/libvmod-dynamic#19]
Hi

I was looking into use saintmode for some static files, but as dynamic do not defines the backends the same way, i'm not sure if it is possible to use it or not.

https://github.com/varnish/varnish-modules/blob/master/src/vmod_saintmode.vcc

So have you any ideia if is possible and how to use both saintmode and dynamic? 

thanks

**Comment by Dridi** [comment]
The short answer is no. I have pondered this problem already but there's no way to integrate this feature as of today. Not without basically copying the saintmode code here, so for now this is not planned.

**Comment by danielmotaleite** [comment]
ok, i suspected that... i will workaround with some VCL code. Thanks for the help!
