### ISSUE TITLE
5.0 branch build fails against varnish 4.1.8

### ISSUE THREAD

**Issue by vStone** [nigoroll/libvmod-dynamic#25]
Building branch 5.0 against varnish-4.1.8:
```
make[2]: Entering directory '/home/jan/SRC/libvmod-dynamic/src'
  VMODTOOL vmod_dynamic.vcc
WARNING: $Event description is not included in .rst:
[(162, '')]
  CC       vmod_dynamic.lo
vmod_dynamic.c: In function ‘dynamic_share_parse’:
vmod_dynamic.c:782:2: error: implicit declaration of function ‘NEEDLESS’ [-Werror=implicit-function-declaration]
  NEEDLESS(return(0));
  ^
vmod_dynamic.c:782:11: error: expected expression before ‘return’
  NEEDLESS(return(0));
           ^
cc1: all warnings being treated as errors
make[2]: *** [Makefile:650: vmod_dynamic.lo] Error 1
```

Maybe split off a bit too late?

**Comment by vStone** [comment]
test13 also fails

````
**   top   2.4 === varnish v1 -cliexpect "d1\\.www\\.localhost.*4/8" "backend.l...
---- v1    2.4 Unknown varnish argument: -cliexpect
```

**Comment by nigoroll** [comment]
Apologies, I had meant to push a 4.1 branch but apparently I hadn't. It's available now and I will re-check 4.1

**Comment by nigoroll** [comment]
vmod-dynamic 4.1 builds fine against varnish-cache 4.1 for me.
But please note that I did not port back the latest changes to 4.1

**Comment by nigoroll** [comment]
Actually getting the newer 5.0 branch to build against 4.1 shouldn't be too hard. I'm working on it.

**Comment by nigoroll** [comment]
I've merged the 5.0 changes into 4.1, which needs a minor change for test13 to work.

**Comment by vStone** [comment]
I just had to change the NEEDLESS to NEEDLESS_RETURN to get it compiling ;)

**Comment by vStone** [comment]
To build on wheezy (yes, I know.... goddamn legacy projects) I also patched configure.ac:
```diff
-AM_INIT_AUTOMAKE([1.12 -Wall -Werror foreign parallel-tests])
+AM_INIT_AUTOMAKE([1.11 -Wall -Werror foreign parallel-tests])
```

Not sure if you are depending on specific 1.12 features of automake

**Comment by nigoroll** [comment]
thx @vStone
