### ISSUE TITLE
Building issue on RHEL7 with varnish 4.1.8

### ISSUE THREAD

**Issue by imanandshah** [nigoroll/libvmod-dynamic#27]
I get the below error while building on a vanilla RHEL varnish 4.1.8 version. Can you help here?? 

> make  all-recursive
make[1]: Entering directory `/var/tmp/libvmod-dynamic'
Making all in src
make[2]: Entering directory `/var/tmp/libvmod-dynamic/src'
  VMODTOOL vmod_dynamic.vcc
WARNING: $Event description is not included in .rst:
[(162, '')]
  CC       vmod_dynamic.lo
vmod_dynamic.c: In function 'dynamic_get':
vmod_dynamic.c:698:2: error: passing argument 2 of 'Lck__New' from incompatible pointer type [-Werror]
  Lck_New(&dom->mtx, lck_be);
  ^
In file included from vmod_dynamic.c:47:0:
/product/varnish/include/varnish/cache/cache.h:828:6: note: expected 'struct VSC_C_lck *' but argument is of type 'struct VSC_lck *'
 void Lck__New(struct lock *lck, struct VSC_C_lck *, const char *);
      ^
vmod_dynamic.c: In function 'vmod_event':
vmod_dynamic.c:732:12: error: assignment from incompatible pointer type [-Werror]
    lck_dir = Lck_CreateClass("dynamic.director");
            ^
vmod_dynamic.c:733:11: error: assignment from incompatible pointer type [-Werror]
    lck_be = Lck_CreateClass("dynamic.backend");
           ^
vmod_dynamic.c:744:4: error: implicit declaration of function 'Lck_DestroyClass' [-Werror=implicit-function-declaration]
    Lck_DestroyClass(&lck_dir);
    ^
vmod_dynamic.c: In function 'dynamic_share_parse':
vmod_dynamic.c:782:2: error: implicit declaration of function 'NEEDLESS' [-Werror=implicit-function-declaration]
  NEEDLESS(return(0));
  ^
vmod_dynamic.c:782:11: error: expected expression before 'return'
  NEEDLESS(return(0));
           ^
vmod_dynamic.c: In function 'vmod_director__init':
vmod_dynamic.c:858:2: error: passing argument 2 of 'Lck__New' from incompatible pointer type [-Werror]
  Lck_New(&obj->mtx, lck_dir);
  ^
In file included from vmod_dynamic.c:47:0:
/product/varnish/include/varnish/cache/cache.h:828:6: note: expected 'struct VSC_C_lck *' but argument is of type 'struct VSC_lck *'
 void Lck__New(struct lock *lck, struct VSC_C_lck *, const char *);
      ^
cc1: all warnings being treated as errors

**Comment by nigoroll** [comment]
Are you sure you are building from the 4.1 branch?

**Comment by nigoroll** [comment]
closing for now, feel free to re-open if your problem persists
