### ISSUE TITLE
Assert error in vca_acct(), cache/cache_acceptor.c line 497 while initailly loading the module

### ISSUE THREAD

**Issue by jpastuszek** [nigoroll/libvmod-dynamic#32]
I am using varnish 4.1.3.
When loading this module into running Varnish instance it crashes on assertion an I lose my cache:
```Assert error in vca_acct(), cache/cache_acceptor.c line 497:   Condition(ls->sock > 0) not true. thread = (cache-acceptor) version = varnish-4.1.3 revision 5e3b6d2 ident = Linux,4.4.16-27.56.amzn1.x86_64,x86_64,-junix,-smalloc,-smalloc,-hcritbit,epoll Backtrace:   0x432f23: varnishd() [0x432f23]   0x40efc0: varnishd(VCA_NewPool+0) [0x40efc0]   0x7f6f5ea69dc5: libpthread.so.0(+0x7dc5) [0x7f6f5ea69dc5]   0x7f6f5e796c9d: libc.so.6(clone+0x6d) [0x7f6f5e796c9d]```
This makes it difficult to introduce it to running system (cache loss).

**Comment by nigoroll** [comment]
I doubt this is related to the _dynamic_ vmod. This looks much more like an issue in varnish-cache which I have worked on recently: https://github.com/varnishcache/varnish-cache/issues/2482
If you think this is a new bug, please provide details on how to reproduce it.

**Comment by nigoroll** [comment]
please reopen if you think there is a genuine bug
