### ISSUE TITLE
ABI mismatch against Varnish 6.0 - RPM package needs a bump?

### ISSUE THREAD

**Issue by slawekm** [nigoroll/libvmod-dynamic#37]
Hi, 

I'm getting ABI mismatch error when running against Varnish 6.0:

```
bash-4.2# /usr/sbin/varnish_reload_vcl
Loading vcl from /etc/varnish/default.vcl
Current running config name is boot
Using new config name reload_2018-03-26T114607
Message from VCC-compiler:
Incompatible VMOD dynamic
	File name: /usr/lib64/varnish/vmods/libvmod_dynamic.so
	ABI mismatch, expected <Varnish 6.0.0 a068361dff0d25a0d85cf82a6e5fdaf315e06a7d>, got <Varnish 5.2.1 67e562482>
('/etc/varnish/default.vcl' Line 60 Pos 8)
import dynamic;
-------#######-

Running VCC-compiler failed, exited with 2
VCL compilation failed
Command failed with error code 106
```

```
bash-4.2# rpm -qi vmod-dynamic
Name        : vmod-dynamic
Version     : 0.3
Release     : 12.el7
Source RPM  : vmod-dynamic-0.3-12.el7.src.rpm
Build Date  : Fri Nov 24 17:17:58 2017
Build Host  : 5f3d6e6b911d
```

Works fine when I've compiled vmod from source.

Thanks.

**Comment by nigoroll** [comment]
Sorry, I am not maintaining the rpm

**Comment by Dridi** [comment]
Just rebuild a new RPM against Varnish 6.

**Comment by slawekm** [comment]
@Dridi Will do. Just assumed that [Uplex repo](https://packagecloud.io/uplex/varnish) is up to date. Thanks.

**Comment by nigoroll** [comment]
@slawekm ah be bad, I am not up to speed with the fact that though not me, WE are providing packages.
Summoning @slimhazard

**Comment by Dridi** [comment]
In the future we hope to fail the package upgrade before you end up in the ABI mismatch situation:

https://github.com/varnishcache/varnish-cache/wiki/VIP20%3A-Varnish-ABI-and-packaging

**Comment by slimhazard** [comment]
I hope to have an updated version of the RPM in the UPLEX repo shortly after Easter.

**Comment by slimhazard** [comment]
New RPMs with version 0.4, compatible with Varnish 6.0.0, are now available at:

https://packagecloud.io/uplex/varnish

The code is on branch 6.0 and tagged as v0.4.
