### ISSUE TITLE
Sometimes vmod_dynamic stops refreshing DNS

### ISSUE THREAD

**Issue by garadox** [nigoroll/libvmod-dynamic#46]
Even using `varnishlog -g raw -q '* ~ vmod-dynamic'` to watch logs of the DNS refresh occurring, I haven't managed to isolate a repeatable scenario where DNS stops being refreshed.

We have docker containers running centos 7 and varnish 4.1.8, and over time some of those containers will stop outputting logs for vmod-dynamic and the backend list will become stale. Eventually if undetected, the backend list has no healthy entries and varnish starts returning 503's.

We have found that killing the varnish child process or using varnishadm to reload the existing vcl is enough to fix the dns lookup and everything is good again.

One thing I will call out is that our DNS ttl is set to 10 seconds, as we're running in kubernetes and pods can go away pretty quickly.

Example VCL:

```
vcl 4.0;

    import std;
    import directors;
    import saintmode;
    import dynamic;
    import xkey;
    import statsd;
    import timers;
    import vsthrottle;
    import header;

    # Default backend definition.
    backend default {
     .host = "0.0.0.0";
     .port = "80";
    }

    probe default_probe {
      .url = "/test";
      .interval = 4s;
      .timeout = 1s;
      .window = 3;
      .threshold = 2;
      .initial = 2;
    }

    sub vcl_init {
      new default_dir = dynamic.director(
        port = "5050",
        probe = default_probe,
        ttl = 10s);

      statsd.server( "127.0.0.1", "8126" );
    }

    
    sub vcl_recv {
      if ( req.method == "GET" || req.method == "HEAD" ) {
        return(hash);
      }
    }

    sub vcl_deliver {
      if (obj.hits > 0) {
        set resp.http.X-CACHE = "hit";
      } else {
        set resp.http.X-CACHE = "miss";
      }
      return (deliver);
    }

    sub vcl_backend_response {
         set beresp.ttl = 2s;
         set beresp.grace = 20s;
         set beresp.keep = 2s;
         if ( beresp.status == 200 || beresp.status == 400 || beresp.status == 404 ) {
          # if s-maxage is not set then set some defaults
          set beresp.ttl = 120s;
          set beresp.grace = 2m;
          set beresp.keep = 0s;
         }
       }
       if (beresp.http.content-type ~ "(text|json|xml|javascript)" ) {
           set beresp.do_gzip = true;
       }
    }

    sub vcl_backend_fetch {
      set bereq.backend = default_dir.backend("example-service");

      return (fetch);
    }

    sub vcl_backend_error {
       set beresp.http.Content-Type = "text/html; charset=utf-8";
       set beresp.http.Retry-After = "5";
       synthetic( {"<!DOCTYPE html>
    <html>
     <head>
       <title>"} + beresp.status + " " + beresp.reason + {"</title>
     </head>
     <body>
       <h1>Error "} + beresp.status + " " + beresp.reason + {"</h1>
       <p>"} + beresp.reason + {"</p>
       <h3>Redsky TX:</h3>
       <p>X-REQUEST-ID: "} + bereq.http.X-REQUEST-ID + {"</p>
       <hr>
       <p>Redsky</p>
     </body>
    </html>
    "} );
       return (deliver);
    }

```

**Comment by nigoroll** [comment]
can you please add the commit id you've built from?

**Comment by nigoroll** [comment]
And it would be interesting to learn if this happens with up-to-date code (6.2)

**Comment by garadox** [comment]
Unfortunately the version of libvmod-dynamic we're using was compiled over 2 years ago and we lost track of the commit it came from.

**Comment by garadox** [comment]
I can tell you it was checked in on 9/20/2017, so this may have been the commit `89f489146f129a841ec91467178b28cea57236df`

**Comment by nigoroll** [comment]
ok, then there are most likely no changes with respect to name resolution

So we need to understand more. Can you please collect

```
varnishlog -g raw -I Error:vmod-dynamic -I Timestamp:vmod-dynamic -I Debug:vmod-dynamic -I VCL_Log:vmod-dynamic
```

consider using the `-w` to write to a file. I am interested in the last lines before resolution stops working.

**Comment by nigoroll** [comment]
More questions:
* can you exclude the possibility that the real time clock is being stepped?
* can you exclude the possibility that you are being hit by https://usn.ubuntu.com/3239-2/ / https://bugs.launchpad.net/ubuntu/+source/glibc/+bug/1674532 ?

**Comment by nigoroll** [comment]
Can you please provide details on the issue?

I will otherwise time out this issue on April 8 or thereafter.

**Comment by garadox** [comment]
I'm collecting vmod-dynamic logs now. Waiting for the issue to show again to provide something useful.
As for excluding the clock being stepped - how would I determine this? Varnish is running in a docker container in a kubernetes cluster - could that be stepping the clock?

The version of glibc supported by centos7 is 2.17, so the first issue could be a factor.
The second issue shouldn't be related as DNS never stops working in the pod (from what I can see).

**Comment by garadox** [comment]
This is all I got from the vmod_dynamic logs:
vmod-dynamic boot.aggregator_dir(aggregator-api-service) Lookup: 1553779896.158353 0.000000 0.000000^@115i^@^@P^@^@^@^@
That last timestamp is about 40 minutes ago, when it last looked up the DNS for this backend.
There are other backends also using vmod_dynamic that are still being updated.

**Comment by nigoroll** [comment]
> ```
> vmod-dynamic boot.aggregator_dir(aggregator-api-service) Lookup: 1553779896.158353 0.000000 0.000000^@115i^@^@P^@^@^@^@
> ```

This looks terribly, terribly wrong. I completely fail to see why we would have such garbage in the log line.

At this point my conclusion would be that there is no evidence for an issue in vmod_dynamic, Ref: https://github.com/nigoroll/libvmod-dynamic/blob/master/src/vmod_dynamic.c#L497

* the next thing after the `Lookup` log line is the `getaddrinfo` call
* followed immediately by `Results` log line

So if the `Results` line never appears, the implication is that `getaddrinfo` never completes, which would be a libc bug - even if we passed it pad parameters it would need to return at least.

On top of all that, you see garbage in your VSL, which is another indication that something very fishy is going on. For example, if we were looking at memory corruption, while that could originate from vmod_dynamic, it might as well originate from any other code in the varnish address space, so, again this is out of scope for vmod_dynamic unless we got more concrete evidence.

So I will close this bug as invalid, please feel free to open if you got any new information pointing towards an inssue in vmod_dynamic.
Otherwise I recommend to consider other support options, for example from https://uplex.de/#anchorvarnish
