### ISSUE TITLE
Least connection support

### ISSUE THREAD

**Issue by danielmotaleite** [nigoroll/libvmod-dynamic#61]
Hi

From what i understand, we have by default round-robin backend policy... Is there any way to switch to least connections?

If one backend locks up or get overload
, with round-robin, varnish will still try to deliver requests, not only overloading it more, but increasing the number of requests that may fail (when finally the healthcheck removes the bad backend) or get bad performance... with least connections, the locked one still will keep some requests, but new ones will be delivered to good backends, avoiding overloading even more the bad backend

thanks

**Comment by nigoroll** [comment]
sure, this could be added, and I would consider pull requests or sponsorships

**Comment by nigoroll** [comment]
timeout
