### ISSUE TITLE
no release works with 7.0.2

### ISSUE THREAD

**Issue by gquintard** [nigoroll/libvmod-dynamic#80]
Unless I'm mistaken, `2.5.0` is the latest tag, and has `VARNISH_PREREQ([6.6.0],[7.0.0])`, preventing it from building again `7.0.2`
I can of course pick the top of master, but I'd like to package this vmod into the official `docker` image, and so having an official tag/release would be nice

**Comment by nigoroll** [comment]
@slimhazard would you want to look after releases?

**Comment by slimhazard** [comment]
@nigoroll will do.

**Comment by slimhazard** [comment]
Tag 2.6.0 on branch 7.0 is compatible with Vanish 7.0.2. It still has VARNISH_PREREQ at minimum 7.0.0, but the RPM packaging has been updated to require 7.0.2. We now have el7 RPMs for version 2.6.0, requiring Varnish 7.0.2, at pkg.uplex.de.

**Comment by gquintard** [comment]
thanks!
