### ISSUE TITLE
A branch dedicated to 7.1?

### ISSUE THREAD

**Issue by anthosz** [nigoroll/libvmod-dynamic#84]
Hello,

Is it planned to create a branch dedicated to 7.1 or we simply need to use master?

Best regards,

**Comment by nigoroll** [comment]
I usually create branches when master receives breaking changes.
So far, I would hope that master works, but I have not tested lately.
At any rate, this vmod still needs to be adopted to director refcounting introducted after 7.0.2

**Comment by anthosz** [comment]
Ok, it's pitty, we have a pipeline that do the compilation depending of this branch.

Will use master if 7.1

Thx!
