### ISSUE TITLE
Branches 7.1 / 7.2

### ISSUE THREAD

**Issue by ronaldploeger** [nigoroll/libvmod-dynamic#94]
Hi, 

will there be a branch 7.1 and 7.2 or does the branch 7.0 work correctly with those versions of varnish? 

Thanks and best regards,
Ronald

**Comment by nigoroll** [comment]
Until right now, the master branch supported 7.1 and 7.2,
As this has now changed, I have created a [7.1 branch](https://github.com/nigoroll/libvmod-dynamic/tree/7.1) which is also for 7.2.

**Comment by ronaldploeger** [comment]
Thank you, Nils
