### ISSUE TITLE
7.3 compatibility

### ISSUE THREAD

**Issue by gquintard** [nigoroll/libvmod-dynamic#96]
hi,

As I'm sure you know, some APIs have changed in Varnish 7.3, and libvmod-dynamic doesn't compile against it. I'm opening this for visibility, and I'll try to look into it this week-end if nobody beats me to it

**Comment by gquintard** [comment]
nevermind, I can just use `master`

**Comment by nigoroll** [comment]
FYI, there _are_ some significant changes since 7.1 which we do not yet make use of, but I am working on changing that. The respective code is not yet pushed, though.
This is mostly regarding reference counting and the new `.release` callback.

**Comment by nigoroll** [comment]
Oh and FWIW, the breaking changes have already been reflected in master, yes.
